FROM php:8.1-apache
RUN echo "deb http://deb.debian.org/debian bullseye main contrib non-free" > /etc/apt/sources.list
RUN apt-get update && \
    apt-get install -y default-mysql-client libzip-dev zip unzip && \
    docker-php-ext-install mysqli pdo_mysql zip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY index.php /var/www/html/index.php
COPY new.php /var/www/html/new.php
COPY redlock-db.sql /docker-entrypoint-initdb.d/redlock-db.sql
RUN chown -R www-data:www-data /var/www/html && \
    chmod -R u+rw,g+rw,o-rwx /var/www/html
CMD ["apache2-foreground"]
